language: python

cache: pip

python:
  - "3.8"

install:
  - pip install -r requirements-dev.txt

before_script:
  - time flake8 rssbot/

script: 'true'

deploy:
  provider: heroku
  api_key:
    secure: ''
  on:
    branch: master
  app:
    master: my-app-staging
    production: my-app-production


notifications:
  email:
    recipients:
      - maxkrivich@gmail.com
    on_success: never
    on_failure: always

# https://docs.travis-ci.com/user/deployment/heroku/