language: python

cache: pip

python:
  - '3.8'

install:
  - pip install -r requirements-ci.txt

before_script:
  - time flake8 rssbot/

script: true

deploy:
  provider: heroku
  api_key:
    secure: LrEmDvilENK1iKGwX1hM40WSXzV7FYMVRSxSah/VBVUzRBuH94UKn7ivtEJdvp0xykkYasL9mGynqlru2DgO2vxc4jZA/yhqaF6cGK/9QpP7IEGN0CKWh1QwimYYfvtywdNO1HIsr157S2NhJ0WUhCQllU5VcP8nzKbPs8wF+APJvJSnDMg/zUg+Tb3JWK1pOSOwSCu6NPk266YN1yNsXp5BsgrwL+wPj2Jdhj4Cnh0wT2XitubrvThFGrIOhCMyth9hrp2AIq0JEFBPL7Tcxkyswdh0N1LNAu2gV3yD97kbKQQmATwbTnYrVtC/tO2x5LpwLwb5gqoGrfNuxEzNlyHCPLlXXxaupkQmwFdMNfDBW16WidXYcesxmzrXXOteROeHiJw37kkFnxxVMLmxOlTuBvcJBUIn0mDXl4bO/BC3GwtKC3CIIRjBqb9cd1onxvEpTjgDyslhBg+1jDKiIvqOsKdO3ieqkGAuxlIudt/dRfwykO58MGbPg0Ni33Nn9mPkGTLJQzMF6XZhlK7nCm6lTF+hqNS6TiwHVKaphiTBYJYyjZFjjrAL6LZCb9oj6XYy4zl9yorCEVK5m0xOuWCT2U4SK4XKmp4ZIBKmk+C47Z01KwM5gDAbCqIvztM0sFGr2mWJopW1Mqf9hq2yY2yQBuB9QWRX38Nhr4jfl0k=
  on:
    branch: master
  app: karazinnews-staging

notifications:
  email:
    recipients:
      - maxkrivich@gmail.com
    on_success: never
    on_failure: always
