version: '3.7'

services:
  postgres:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_DB: rssbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: